### ISSUE TITLE
Error: [auto-import] identifier useImperativeHandle already defined with react

### ISSUE THREAD

**Issue by ryuujo1573** [yunsii/vite-react#10]
using latest `master` branch and after 
```bash
pnpm i; pnpm dev
```
then I ran into the problem. 
Here's [my project](https://github.com/ryuujo1573/foodSDU/tree/master).

Thank you.

**Comment by yunsii** [comment]
https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/react.ts has contains the project custom auto-import https://github.com/yunsii/vite-react/blob/master/vite.config.ts#L27

So, you can use `autoImport` plugin directly without custom `imports`

**Comment by ryuujo1573** [comment]
Nonetheless I was cloning without significant modification, ran into runtime error finally.
I was wondering why this would happen.
```
failed to load config from /Users/_____/foodSDU/vite.config.ts
error when starting dev server:
Error: [auto-import] identifier useImperativeHandle already defined with react
    at /Users/_____/foodSDU/node_modules/.pnpm/registry.npmmirror.com+unplugin-auto-import@0.6.9_vite@2.9.14/node_modules/unplugin-auto-import/dist/chunk-KSE6FVK6.js:63:17
    at Array.forEach (<anonymous>)
    at flattenImportsMap (/Users/_____/foodSDU/node_modules/.pnpm/registry.npmmirror.com+unplugin-auto-import@0.6.9_vite@2.9.14/node_modules/unplugin-auto-import/dist/chunk-KSE6FVK6.js:42:36)
    at resolveOptions (/Users/_____/foodSDU/node_modules/.pnpm/registry.npmmirror.com+unplugin-auto-import@0.6.9_vite@2.9.14/node_modules/unplugin-auto-import/dist/chunk-KSE6FVK6.js:18:19)
    at /Users/_____/foodSDU/node_modules/.pnpm/registry.npmmirror.com+unplugin-auto-import@0.6.9_vite@2.9.14/node_modules/unplugin-auto-import/dist/chunk-KSE6FVK6.js:235:18
    at /Users/_____/foodSDU/node_modules/.pnpm/registry.npmmirror.com+unplugin@0.4.0_vite@2.9.14/node_modules/unplugin/dist/index.js:965:23
    at Object.<anonymous> (/Users/_____/foodSDU/vite.config.ts:97:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions.<computed> [as .ts] (/Users/_____/foodSDU/node_modules/.pnpm/registry.npmmirror.com+vite@2.9.14_less@4.1.3/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61998:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ryuujo1573** [comment]
Using `pnpm` might cause the error.

I've turned to `yarn` and added two peer deps
> `prop-types@^15.5.7`
> `rollup@^2.0.0`

This fixed the problem. Thank you.

**Comment by yunsii** [comment]
Yep, the project has `yarn.lock`, use `yarn` will be ok.
